import { Surah, Dua } from './types';
import { DUAS as dataDuas } from './data/duas';

export const DUAS: Dua[] = dataDuas;

export const SURAHS: Surah[] = [
  { number: 1, name: "الفاتحة", englishName: "Al-Fatiha", englishNameTranslation: "فاتحة الكتاب", numberOfAyahs: 7, revelationType: "مكية", startPage: 1, pdfUrl: "/pdfs/1.pdf" },
  { number: 2, name: "البقرة", englishName: "Al-Baqarah", englishNameTranslation: "سنام القرآن", numberOfAyahs: 286, revelationType: "مدنية", startPage: 2, pdfUrl: "/pdfs/2.pdf" },
  { number: 3, name: "آل عمران", englishName: "Al-Imran", englishNameTranslation: "العمرانية", numberOfAyahs: 200, revelationType: "مدنية", startPage: 50, pdfUrl: "/pdfs/3.pdf" },
  { number: 4, name: "النساء", englishName: "An-Nisa", englishNameTranslation: "النساء الكبرى", numberOfAyahs: 176, revelationType: "مدنية", startPage: 77, pdfUrl: "/pdfs/4.pdf" },
  { number: 5, name: "المائدة", englishName: "Al-Ma'idah", englishNameTranslation: "العقود", numberOfAyahs: 120, revelationType: "مدنية", startPage: 106, pdfUrl: "/pdfs/5.pdf" },
  { number: 6, name: "الأنعام", englishName: "Al-An'am", englishNameTranslation: "الأنعام", numberOfAyahs: 165, revelationType: "مكية", startPage: 128, pdfUrl: "/pdfs/6.pdf" },
  { number: 7, name: "الأعراف", englishName: "Al-A'raf", englishNameTranslation: "الميثاق", numberOfAyahs: 206, revelationType: "مكية", startPage: 151, pdfUrl: "/pdfs/7.pdf" },
  { number: 8, name: "الأنفال", englishName: "Al-Anfal", englishNameTranslation: "بدر", numberOfAyahs: 75, revelationType: "مدنية", startPage: 177, pdfUrl: "/pdfs/8.pdf" },
  { number: 9, name: "التوبة", englishName: "At-Tawbah", englishNameTranslation: "البراءة", numberOfAyahs: 129, revelationType: "مدنية", startPage: 187, pdfUrl: "/pdfs/9.pdf" },
  { number: 10, name: "يونس", englishName: "Yunus", englishNameTranslation: "يونس", numberOfAyahs: 109, revelationType: "مكية", startPage: 208, pdfUrl: "/pdfs/10.pdf" },
  { number: 11, name: "هود", englishName: "Hud", englishNameTranslation: "هود", numberOfAyahs: 123, revelationType: "مكية", startPage: 221, pdfUrl: "/pdfs/11.pdf" },
  { number: 12, name: "يوسف", englishName: "Yusuf", englishNameTranslation: "أحسن القصص", numberOfAyahs: 111, revelationType: "مكية", startPage: 235, pdfUrl: "/pdfs/12.pdf" },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", englishNameTranslation: "الرعد", numberOfAyahs: 43, revelationType: "مدنية", startPage: 249, pdfUrl: "/pdfs/13.pdf" },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", englishNameTranslation: "إبراهيم", numberOfAyahs: 52, revelationType: "مكية", startPage: 255, pdfUrl: "/pdfs/14.pdf" },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", englishNameTranslation: "الحجر", numberOfAyahs: 99, revelationType: "مكية", startPage: 262, pdfUrl: "/pdfs/15.pdf" },
  { number: 16, name: "النحل", englishName: "An-Nahl", englishNameTranslation: "النعم", numberOfAyahs: 128, revelationType: "مكية", startPage: 267, pdfUrl: "/pdfs/16.pdf" },
  { number: 17, name: "الإسراء", englishName: "Al-Isra", englishNameTranslation: "بني إسرائيل", numberOfAyahs: 111, revelationType: "مكية", startPage: 282, pdfUrl: "/pdfs/17.pdf" },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", englishNameTranslation: "أصحاب الكهف", numberOfAyahs: 110, revelationType: "مكية", startPage: 293, pdfUrl: "/pdfs/18.pdf" },
  { number: 19, name: "مريم", englishName: "Maryam", englishNameTranslation: "مريم", numberOfAyahs: 98, revelationType: "مكية", startPage: 305, pdfUrl: "/pdfs/19.pdf" },
  { number: 20, name: "طه", englishName: "Taha", englishNameTranslation: "طه", numberOfAyahs: 135, revelationType: "مكية", startPage: 312, pdfUrl: "/pdfs/20.pdf" },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", englishNameTranslation: "الأنبياء", numberOfAyahs: 112, revelationType: "مكية", startPage: 322, pdfUrl: "/pdfs/21.pdf" },
  { number: 22, name: "الحج", englishName: "Al-Hajj", englishNameTranslation: "الحج", numberOfAyahs: 78, revelationType: "مدنية", startPage: 332, pdfUrl: "/pdfs/22.pdf" },
  { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", englishNameTranslation: "المؤمنون", numberOfAyahs: 118, revelationType: "مكية", startPage: 342, pdfUrl: "/pdfs/23.pdf" },
  { number: 24, name: "النور", englishName: "An-Nur", englishNameTranslation: "النور", numberOfAyahs: 64, revelationType: "مدنية", startPage: 350, pdfUrl: "/pdfs/24.pdf" },
  { number: 25, name: "الفرقان", englishName: "Al-Furqan", englishNameTranslation: "الفرقان", numberOfAyahs: 77, revelationType: "مكية", startPage: 359, pdfUrl: "/pdfs/25.pdf" },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", englishNameTranslation: "الجامعة", numberOfAyahs: 227, revelationType: "مكية", startPage: 367, pdfUrl: "/pdfs/26.pdf" },
  { number: 27, name: "النمل", englishName: "An-Naml", englishNameTranslation: "الهدهد", numberOfAyahs: 93, revelationType: "مكية", startPage: 377, pdfUrl: "/pdfs/27.pdf" },
  { number: 28, name: "القصص", englishName: "Al-Qasas", englishNameTranslation: "القصص", numberOfAyahs: 88, revelationType: "مكية", startPage: 385, pdfUrl: "/pdfs/28.pdf" },
  { number: 29, name: "العنكبوت", englishName: "Al-Ankabut", englishNameTranslation: "العنكبوت", numberOfAyahs: 69, revelationType: "مكية", startPage: 396, pdfUrl: "/pdfs/29.pdf" },
  { number: 30, name: "الروم", englishName: "Ar-Rum", englishNameTranslation: "الروم", numberOfAyahs: 60, revelationType: "مكية", startPage: 404, pdfUrl: "/pdfs/30.pdf" },
  { number: 31, name: "لقمان", englishName: "Luqman", englishNameTranslation: "لقمان", numberOfAyahs: 34, revelationType: "مكية", startPage: 411, pdfUrl: "/pdfs/31.pdf" },
  { number: 32, name: "السجدة", englishName: "As-Sajdah", englishNameTranslation: "المضاجع", numberOfAyahs: 30, revelationType: "مكية", startPage: 415, pdfUrl: "/pdfs/32.pdf" },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", englishNameTranslation: "الأحزاب", numberOfAyahs: 73, revelationType: "مدنية", startPage: 418, pdfUrl: "/pdfs/33.pdf" },
  { number: 34, name: "سبأ", englishName: "Saba", englishNameTranslation: "سبأ", numberOfAyahs: 54, revelationType: "مكية", startPage: 428, pdfUrl: "/pdfs/34.pdf" },
  { number: 35, name: "فاطر", englishName: "Fatir", englishNameTranslation: "الملائكة", numberOfAyahs: 45, revelationType: "مكية", startPage: 434, pdfUrl: "/pdfs/35.pdf" },
  { number: 36, name: "يس", englishName: "Ya-Sin", englishNameTranslation: "قلب القرآن", numberOfAyahs: 83, revelationType: "مكية", startPage: 440, pdfUrl: "/pdfs/36.pdf" },
  { number: 37, name: "الصافات", englishName: "As-Saffat", englishNameTranslation: "الصافات", numberOfAyahs: 182, revelationType: "مكية", startPage: 446, pdfUrl: "/pdfs/37.pdf" },
  { number: 38, name: "ص", englishName: "Sad", englishNameTranslation: "ص", numberOfAyahs: 88, revelationType: "مكية", startPage: 453, pdfUrl: "/pdfs/38.pdf" },
  { number: 39, name: "الزمر", englishName: "Az-Zumar", englishNameTranslation: "الغرف", numberOfAyahs: 75, revelationType: "مكية", startPage: 458, pdfUrl: "/pdfs/39.pdf" },
  { number: 40, name: "غافر", englishName: "Ghafir", englishNameTranslation: "المؤمن", numberOfAyahs: 85, revelationType: "مكية", startPage: 467, pdfUrl: "/pdfs/40.pdf" },
  { number: 41, name: "فصلت", englishName: "Fussilat", englishNameTranslation: "حم السجدة", numberOfAyahs: 54, revelationType: "مكية", startPage: 477, pdfUrl: "/pdfs/41.pdf" },
  { number: 42, name: "الشورى", englishName: "Ash-Shura", englishNameTranslation: "الشورى", numberOfAyahs: 53, revelationType: "مكية", startPage: 483, pdfUrl: "/pdfs/42.pdf" },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", englishNameTranslation: "الزخرف", numberOfAyahs: 89, revelationType: "مكية", startPage: 489, pdfUrl: "/pdfs/43.pdf" },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhan", englishNameTranslation: "الدخان", numberOfAyahs: 59, revelationType: "مكية", startPage: 496, pdfUrl: "/pdfs/44.pdf" },
  { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", englishNameTranslation: "الشريعة", numberOfAyahs: 37, revelationType: "مكية", startPage: 499, pdfUrl: "/pdfs/45.pdf" },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", englishNameTranslation: "الأحقاف", numberOfAyahs: 35, revelationType: "مكية", startPage: 502, pdfUrl: "/pdfs/46.pdf" },
  { number: 47, name: "محمد", englishName: "Muhammad", englishNameTranslation: "القتال", numberOfAyahs: 38, revelationType: "مدنية", startPage: 507, pdfUrl: "/pdfs/47.pdf" },
  { number: 48, name: "الفتح", englishName: "Al-Fath", englishNameTranslation: "الفتح", numberOfAyahs: 29, revelationType: "مدنية", startPage: 511, pdfUrl: "/pdfs/48.pdf" },
  { number: 49, name: "الحجرات", englishName: "Al-Hujurat", englishNameTranslation: "الأخلاق", numberOfAyahs: 18, revelationType: "مدنية", startPage: 515, pdfUrl: "/pdfs/49.pdf" },
  { number: 50, name: "ق", englishName: "Qaf", englishNameTranslation: "ق", numberOfAyahs: 45, revelationType: "مكية", startPage: 518, pdfUrl: "/pdfs/50.pdf" },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", englishNameTranslation: "الذاريات", numberOfAyahs: 60, revelationType: "مكية", startPage: 520, pdfUrl: "/pdfs/51.pdf" },
  { number: 52, name: "الطور", englishName: "At-Tur", englishNameTranslation: "الطور", numberOfAyahs: 49, revelationType: "مكية", startPage: 523, pdfUrl: "/pdfs/52.pdf" },
  { number: 53, name: "النجم", englishName: "An-Najm", englishNameTranslation: "النجم", numberOfAyahs: 62, revelationType: "مكية", startPage: 526, pdfUrl: "/pdfs/53.pdf" },
  { number: 54, name: "القمر", englishName: "Al-Qamar", englishNameTranslation: "اقتربت", numberOfAyahs: 55, revelationType: "مكية", startPage: 528, pdfUrl: "/pdfs/54.pdf" },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahman", englishNameTranslation: "عروس القرآن", numberOfAyahs: 78, revelationType: "مدنية", startPage: 531, pdfUrl: "/pdfs/55.pdf" },
  { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", englishNameTranslation: "الواقعة", numberOfAyahs: 96, revelationType: "مكية", startPage: 534, pdfUrl: "/pdfs/56.pdf" },
  { number: 57, name: "الحديد", englishName: "Al-Hadid", englishNameTranslation: "الحديد", numberOfAyahs: 29, revelationType: "مدنية", startPage: 537, pdfUrl: "/pdfs/57.pdf" },
  { number: 58, name: "المجادلة", englishName: "Al-Mujadila", englishNameTranslation: "قد سمع", numberOfAyahs: 22, revelationType: "مدنية", startPage: 542, pdfUrl: "/pdfs/58.pdf" },
  { number: 59, name: "الحشر", englishName: "Al-Hashr", englishNameTranslation: "بني النضير", numberOfAyahs: 24, revelationType: "مدنية", startPage: 545, pdfUrl: "/pdfs/59.pdf" },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", englishNameTranslation: "المودة", numberOfAyahs: 13, revelationType: "مدنية", startPage: 549, pdfUrl: "/pdfs/60.pdf" },
  { number: 61, name: "الصف", englishName: "As-Saff", englishNameTranslation: "الحواريين", numberOfAyahs: 14, revelationType: "مدنية", startPage: 551, pdfUrl: "/pdfs/61.pdf" },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", englishNameTranslation: "الجمعة", numberOfAyahs: 11, revelationType: "مدنية", startPage: 553, pdfUrl: "/pdfs/62.pdf" },
  { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", englishNameTranslation: "المنافقون", numberOfAyahs: 11, revelationType: "مدنية", startPage: 554, pdfUrl: "/pdfs/63.pdf" },
  { number: 64, name: "التغابن", englishName: "At-Taghabun", englishNameTranslation: "التغابن", numberOfAyahs: 18, revelationType: "مدنية", startPage: 556, pdfUrl: "/pdfs/64.pdf" },
  { number: 65, name: "الطلاق", englishName: "At-Talaq", englishNameTranslation: "النساء الصغرى", numberOfAyahs: 12, revelationType: "مدنية", startPage: 558, pdfUrl: "/pdfs/65.pdf" },
  { number: 66, name: "التحريم", englishName: "At-Tahrim", englishNameTranslation: "يا أيها النبي", numberOfAyahs: 12, revelationType: "مدنية", startPage: 560, pdfUrl: "/pdfs/66.pdf" },
  { number: 67, name: "الملك", englishName: "Al-Mulk", englishNameTranslation: "تبارك", numberOfAyahs: 30, revelationType: "مكية", startPage: 562, pdfUrl: "/pdfs/67.pdf" },
  { number: 68, name: "القلم", englishName: "Al-Qalam", englishNameTranslation: "ن والقلم", numberOfAyahs: 52, revelationType: "مكية", startPage: 564, pdfUrl: "/pdfs/68.pdf" },
  { number: 69, name: "الحاقة", englishName: "Al-Haqqah", englishNameTranslation: "الحاقة", numberOfAyahs: 52, revelationType: "مكية", startPage: 566, pdfUrl: "/pdfs/69.pdf" },
  { number: 70, name: "المعارج", englishName: "Al-Ma'arij", englishNameTranslation: "سأل سائل", numberOfAyahs: 44, revelationType: "مكية", startPage: 568, pdfUrl: "/pdfs/70.pdf" },
  { number: 71, name: "نوح", englishName: "Nuh", englishNameTranslation: "نوح", numberOfAyahs: 28, revelationType: "مكية", startPage: 570, pdfUrl: "/pdfs/71.pdf" },
  { number: 72, name: "الجن", englishName: "Al-Jinn", englishNameTranslation: "الجن", numberOfAyahs: 28, revelationType: "مكية", startPage: 572, pdfUrl: "/pdfs/72.pdf" },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil", englishNameTranslation: "المزمل", numberOfAyahs: 20, revelationType: "مكية", startPage: 574, pdfUrl: "/pdfs/73.pdf" },
  { number: 74, name: "المدثر", englishName: "Al-Muddathir", englishNameTranslation: "المدثر", numberOfAyahs: 56, revelationType: "مكية", startPage: 575, pdfUrl: "/pdfs/74.pdf" },
  { number: 75, name: "القيامة", englishName: "Al-Qiyamah", englishNameTranslation: "لا أقسم", numberOfAyahs: 40, revelationType: "مكية", startPage: 577, pdfUrl: "/pdfs/75.pdf" },
  { number: 76, name: "الإنسان", englishName: "Al-Insan", englishNameTranslation: "الدهر", numberOfAyahs: 31, revelationType: "مدنية", startPage: 578, pdfUrl: "/pdfs/76.pdf" },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalat", englishNameTranslation: "العرف", numberOfAyahs: 50, revelationType: "مكية", startPage: 580, pdfUrl: "/pdfs/77.pdf" },
  { number: 78, name: "النبأ", englishName: "An-Naba", englishNameTranslation: "يساءلون", numberOfAyahs: 40, revelationType: "مكية", startPage: 582, pdfUrl: "/pdfs/78.pdf" },
  { number: 79, name: "النازعات", englishName: "An-Nazi'at", englishNameTranslation: "الساهرة", numberOfAyahs: 46, revelationType: "مكية", startPage: 583, pdfUrl: "/pdfs/79.pdf" },
  { number: 80, name: "عبس", englishName: "Abasa", englishNameTranslation: "الصاخة", numberOfAyahs: 42, revelationType: "مكية", startPage: 585, pdfUrl: "/pdfs/80.pdf" },
  { number: 81, name: "التكوير", englishName: "At-Takwir", englishNameTranslation: "التكوير", numberOfAyahs: 29, revelationType: "مكية", startPage: 586, pdfUrl: "/pdfs/81.pdf" },
  { number: 82, name: "الانفطار", englishName: "Al-Infitar", englishNameTranslation: "الانفطار", numberOfAyahs: 19, revelationType: "مكية", startPage: 587, pdfUrl: "/pdfs/82.pdf" },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", englishNameTranslation: "التطفيف", numberOfAyahs: 36, revelationType: "مكية", startPage: 587, pdfUrl: "/pdfs/83.pdf" },
  { number: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", englishNameTranslation: "الانشقاق", numberOfAyahs: 25, revelationType: "مكية", startPage: 589, pdfUrl: "/pdfs/84.pdf" },
  { number: 85, name: "البروج", englishName: "Al-Buruj", englishNameTranslation: "البروج", numberOfAyahs: 22, revelationType: "مكية", startPage: 590, pdfUrl: "/pdfs/85.pdf" },
  { number: 86, name: "الطارق", englishName: "At-Tariq", englishNameTranslation: "الطارق", numberOfAyahs: 17, revelationType: "مكية", startPage: 591, pdfUrl: "/pdfs/86.pdf" },
  { number: 87, name: "الأعلى", englishName: "Al-A'la", englishNameTranslation: "الأعلى", numberOfAyahs: 19, revelationType: "مكية", startPage: 591, pdfUrl: "/pdfs/87.pdf" },
  { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", englishNameTranslation: "الغاشية", numberOfAyahs: 26, revelationType: "مكية", startPage: 592, pdfUrl: "/pdfs/88.pdf" },
  { number: 89, name: "الفجر", englishName: "Al-Fajr", englishNameTranslation: "الفجر", numberOfAyahs: 30, revelationType: "مكية", startPage: 593, pdfUrl: "/pdfs/89.pdf" },
  { number: 90, name: "البلد", englishName: "Al-Balad", englishNameTranslation: "البلد", numberOfAyahs: 20, revelationType: "مكية", startPage: 594, pdfUrl: "/pdfs/90.pdf" },
  { number: 91, name: "الشمس", englishName: "Ash-Shams", englishNameTranslation: "الشمس", numberOfAyahs: 15, revelationType: "مكية", startPage: 595, pdfUrl: "/pdfs/91.pdf" },
  { number: 92, name: "الليل", englishName: "Al-Lail", englishNameTranslation: "الليل", numberOfAyahs: 21, revelationType: "مكية", startPage: 595, pdfUrl: "/pdfs/92.pdf" },
  { number: 93, name: "الضحى", englishName: "Ad-Duha", englishNameTranslation: "الضحى", numberOfAyahs: 11, revelationType: "مكية", startPage: 596, pdfUrl: "/pdfs/93.pdf" },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh", englishNameTranslation: "الانشراح", numberOfAyahs: 8, revelationType: "مكية", startPage: 596, pdfUrl: "/pdfs/94.pdf" },
  { number: 95, name: "التين", englishName: "At-Tin", englishNameTranslation: "التين", numberOfAyahs: 8, revelationType: "مكية", startPage: 597, pdfUrl: "/pdfs/95.pdf" },
  { number: 96, name: "العلق", englishName: "Al-Alaq", englishNameTranslation: "اقرأ", numberOfAyahs: 19, revelationType: "مكية", startPage: 597, pdfUrl: "/pdfs/96.pdf" },
  { number: 97, name: "القدر", englishName: "Al-Qadr", englishNameTranslation: "القدر", numberOfAyahs: 5, revelationType: "مكية", startPage: 598, pdfUrl: "/pdfs/97.pdf" },
  { number: 98, name: "البينة", englishName: "Al-Bayyinah", englishNameTranslation: "البرية", numberOfAyahs: 8, revelationType: "مدنية", startPage: 598, pdfUrl: "/pdfs/98.pdf" },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", englishNameTranslation: "الزلزلة", numberOfAyahs: 8, revelationType: "مدنية", startPage: 599, pdfUrl: "/pdfs/99.pdf" },
  { number: 100, name: "العاديات", englishName: "Al-Adiyat", englishNameTranslation: "العاديات", numberOfAyahs: 11, revelationType: "مكية", startPage: 599, pdfUrl: "/pdfs/100.pdf" },
  { number: 101, name: "القارعة", englishName: "Al-Qari'ah", englishNameTranslation: "القارعة", numberOfAyahs: 11, revelationType: "مكية", startPage: 600, pdfUrl: "/pdfs/101.pdf" },
  { number: 102, name: "التكاثر", englishName: "At-Takathur", englishNameTranslation: "التكاثر", numberOfAyahs: 8, revelationType: "مكية", startPage: 600, pdfUrl: "/pdfs/102.pdf" },
  { number: 103, name: "العصر", englishName: "Al-Asr", englishNameTranslation: "العصر", numberOfAyahs: 3, revelationType: "مكية", startPage: 601, pdfUrl: "/pdfs/103.pdf" },
  { number: 104, name: "الهمزة", englishName: "Al-Humazah", englishNameTranslation: "الهمزة", numberOfAyahs: 9, revelationType: "مكية", startPage: 601, pdfUrl: "/pdfs/104.pdf" },
  { number: 105, name: "الفيل", englishName: "Al-Fil", englishNameTranslation: "الأصحاب", numberOfAyahs: 5, revelationType: "مكية", startPage: 601, pdfUrl: "/pdfs/105.pdf" },
  { number: 106, name: "قريش", englishName: "Quraish", englishNameTranslation: "قريش", numberOfAyahs: 4, revelationType: "مكية", startPage: 602, pdfUrl: "/pdfs/106.pdf" },
  { number: 107, name: "الماعون", englishName: "Al-Ma'un", englishNameTranslation: "الدين", numberOfAyahs: 7, revelationType: "مكية", startPage: 602, pdfUrl: "/pdfs/107.pdf" },
  { number: 108, name: "الكوثر", englishName: "Al-Kauthar", englishNameTranslation: "الخير الكثير", numberOfAyahs: 3, revelationType: "مكية", startPage: 602, pdfUrl: "/pdfs/108.pdf" },
  { number: 109, name: "الكافرون", englishName: "Al-Kafirun", englishNameTranslation: "الكافرون", numberOfAyahs: 6, revelationType: "مكية", startPage: 603, pdfUrl: "/pdfs/109.pdf" },
  { number: 110, name: "النصر", englishName: "An-Nasr", englishNameTranslation: "الفتح", numberOfAyahs: 3, revelationType: "مدنية", startPage: 603, pdfUrl: "/pdfs/110.pdf" },
  { number: 111, name: "المسد", englishName: "Al-Masad", englishNameTranslation: "تّبت", numberOfAyahs: 5, revelationType: "مكية", startPage: 603, pdfUrl: "/pdfs/111.pdf" },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", englishNameTranslation: "التوحيد", numberOfAyahs: 4, revelationType: "مكية", startPage: 604, pdfUrl: "/pdfs/112.pdf" },
  { number: 113, name: "الفلق", englishName: "Al-Falaq", englishNameTranslation: "الفلق", numberOfAyahs: 5, revelationType: "مكية", startPage: 604, pdfUrl: "/pdfs/113.pdf" },
  { number: 114, name: "الناس", englishName: "An-Nas", englishNameTranslation: "الناس", numberOfAyahs: 6, revelationType: "مكية", startPage: 604, pdfUrl: "/pdfs/114.pdf" }
];
